### ISSUE TITLE
Problem with has_shortened_urls in the model.

### ISSUE THREAD

**Issue by nCore** [jpmcgrath/shortener#12]
Hi. 

I went through installation guidelines, but when I add has_shortened_url to my model I can't start server.

I've got this instead:
`/Users/nCore/.rvm/gems/ruby-1.9.2-p290@test-project/gems/activerecord-3.2.6/lib/active_record/dynamic_matchers.rb:50:in 'method_missing': undefined local variable or method 'has_shortened_urls' for #<Class:0x007faded9621a0> (NameError)`

I'm working on Macbook (OS 10.8.3), Rails 3.2.6, ruby 1.9.2-p290 and Thin rails gem (as webserver).

I tried to turn off Thin, but this doesn't help at all.

Any help will be appreciated.
